### ISSUE TITLE
Provider and Member reports must be individual

### ISSUE THREAD

**Issue by thuselem** [Gilmore-PDX-CS/Group9#103]
Currently a summary report for all providers and members is printed. These reports need to be for an _individual_ member or provider.

The project description states:

> Each member who has consulted a ChocAn provider during that week receives a list of services provided to that member, sorted in order of service date.

> Each provider who has billed ChocAn during that week receives a report, sent as an e-mail attachment, containing the list of services he or she provided to ChocAn members.

Further down, the project description states:

> Each member report must be written to its own file; the name of the file should begin with the member name followed by the date of the report. The provider reports should be handled in the same way.

Perhaps we can prompt the manager for the Patient or Provider they want a report on?

**Comment by andy-keene** [comment]
Done. Also everything writes to its own folder then file.
