### ISSUE TITLE
Patient report prints Provider ID instead of Provider name

### ISSUE THREAD

**Issue by thuselem** [Gilmore-PDX-CS/Group9#104]
In the breakdown of each service, it looks like the Provider ID is printed instead of the Provider name.

**Comment by andy-keene** [comment]
<img width="338" alt="screen shot 2016-11-26 at 3 01 22 pm" src="https://cloud.githubusercontent.com/assets/20017363/20644442/3a6d4cf4-b3e9-11e6-9af4-df218b7706d3.png">
