### ISSUE TITLE
Fix Service toString()

### ISSUE THREAD

**Issue by andy-keene** [Gilmore-PDX-CS/Group9#36]
Please return service as string with labeled fields, and with fee printed to two decimal places. Something like 
"Status: Valid
Code: 12031
fee: $12.00
Name: Massaging
.... "

**Comment by thuselem** [comment]
Got it. Will do.

**Comment by thuselem** [comment]
Fix submitted on [PR #52](https://github.com/Gilmore-PDX-CS/Group9/pull/52).
