### ISSUE TITLE
Add Operator and Manager logins

### ISSUE THREAD

**Issue by thuselem** [Gilmore-PDX-CS/Group9#62]
Operator and Manager will need a logins at some point. I will ask the client if they want a sample database or default logins.

**Comment by andy-keene** [comment]
Is this necessary? We don't have Manager or Operator information in the database, so this would be a hard-coded constant in the program.

**Comment by thuselem** [comment]
We asked the client the following:

> Do Operators or Managers have logins or IDs?

Their response:

> Yes they have their own logins.

**Comment by andy-keene** [comment]
Manager is 11235813  (first 7 of fib sequence)
Operator is 23571113 (first 6 primes)

Both hint at what the "password" is

**Comment by thuselem** [comment]
Nice, I like it!
