### ISSUE TITLE
New Provider and Patient status should default to Active

### ISSUE THREAD

**Issue by thuselem** [Gilmore-PDX-CS/Group9#63]
When adding a new Provider or Patient, their `status` should default to Active. Currently, the operator is prompted to select a status, but since `status` indicates the instance is deleted in the database, there should not be an option.

**Comment by mbottini** [comment]
If you need this to change in the DB to give the option of starting as inactive, it's one line of code. That being said, I think that starting as inactive makes no sense - why would you enroll as an inactive participant?

**Comment by thuselem** [comment]
I wrote the wrong one in the title. Default should be Active. Title updated.

**Comment by andy-keene** [comment]
This is done on my side. Is separately dependent on an update from M. Bottini
