### ISSUE TITLE
Running CA from the terminal

### ISSUE THREAD

**Issue by thuselem** [Gilmore-PDX-CS/Group9#66]
We need clear instructions or a script to build and run the CA application from a terminal window. The final product should run in the terminal, and we should run glassbox and system tests this way as well.

**Comment by mbottini** [comment]
The regular CA application shouldn't be hard to do, but the tests have been a pain in the ass to put into the command line. I'll have to do some more digging to see what we can do.

**Comment by thuselem** [comment]
I think we are fine only running unit tests in our IDEs. This would only be for QA where you are not inspecting the code... which means I should not have said glassbox testing above. Yup, make that _blackbox_ and system testing.

**Comment by mbottini** [comment]
See Pull Request #86. Hope you like Linux, Cygwin, or Bash for Windows.
