### ISSUE TITLE
Add Patient to testDB with Inactive FinancialStanding

### ISSUE THREAD

**Issue by thuselem** [Gilmore-PDX-CS/Group9#67]
We need to test validation messages, but we have no "invalid" members. That is, members whose Financial Standing is inactive. Could you please add a couple.

**Comment by evsiretanu** [comment]
Do you mean add to .csv?

**Comment by thuselem** [comment]
Yes. I think DBTest.java uses .csv to build up the testDB, right? We are using this DB as our starting point during testing.

**Comment by evsiretanu** [comment]
Yes.
