### ISSUE TITLE
Patient ID Input doesn't print correct validation

### ISSUE THREAD

**Issue by lc893** [Gilmore-PDX-CS/Group9#68]
When a valid Patient ID is entered, "Validated" is supposed to be printed. Otherwise, "Invalid Number" or "Member suspended" (member's financial standing is inactive) is supposed to be printed.

**Comment by thuselem** [comment]
See [Issue 71](https://github.com/Gilmore-PDX-CS/Group9/issues/72) which references pre-validation. These messages should appear during the pre-validation process. Once a consultation is started, "Validated" should be printed, but we are past the other ones.
