### ISSUE TITLE
Add better Patient confirmation message

### ISSUE THREAD

**Issue by thuselem** [Gilmore-PDX-CS/Group9#69]
Could we add a better message to clarify yes/no prompt. Currently:
```
Financial Standing: Active
 (Yes/No):No
```
Please change to:
```
Financial Standing: Active
 Correct patient? (Yes/No): No
```
Note the added space after the colon.

**Comment by andy-keene** [comment]
When does this prompt display?

**Comment by thuselem** [comment]
After you enter a patient ID, under the options "Check in a patient" and "Start a new consultation" in the Provider terminal.

**Comment by andy-keene** [comment]
This appears to be fixed by @jviel ? 
Closing the issue
<img width="304" alt="screen shot 2016-11-25 at 12 55 50 pm" src="https://cloud.githubusercontent.com/assets/20017363/20635192/b40036a2-b30e-11e6-87c8-3ef33308a25b.png">
