### ISSUE TITLE
Improve printing of Provider Directory

### ISSUE THREAD

**Issue by thuselem** [Gilmore-PDX-CS/Group9#74]
The Provider Directory printout would look nicer if it printed like a table. For example:
```
Code      Name                    Fee           Status
100000    Service Dog             $10.00        Active  
100001    Massage                 $200.00       Inactive
...
```
I think this would call for a single line printed as the table headers by the Terminal, and changing `toString` in the Service class. 

The tricky bit would be getting the spacing right. `Code` is 6 characters long, `Name` is 20, `Fee` is 8, and `Status` is 6 at most (for "Inactive"). This plus some spacing inbetween each could make this look really clean.

**Comment by thuselem** [comment]
Pull request in for these changes. The Terminal needs to print the headers before each request for the Provider Directory. The following will print with the correct spacing:
```
String headers = String.format("%-9s %-23s %-11s %-6s", "Code", "Service Name", "Fee", "Status");
System.out.println(headers);
```

**Comment by andy-keene** [comment]
Fixed this.
<img width="382" alt="screen shot 2016-11-25 at 1 33 29 pm" src="https://cloud.githubusercontent.com/assets/20017363/20635586/c8793d54-b313-11e6-9abd-33ba1e980a13.png">
