### ISSUE TITLE
Service Verification

### ISSUE THREAD

**Issue by thuselem** [Gilmore-PDX-CS/Group9#77]
Ok, this one seems a little heavy-handed, but the Project Description states the following in the section where the Provider is adding Services:

> For verification purposes, the provider has a form on which to enter the current date and time, the date the service was provide, member name and number, service code, and fee to be paid.

And this is supposed to occur after each Service is entered. Do you all think I am reading this right?

**Comment by andy-keene** [comment]
Sounds like they write it down themselves. That's how I've been reading that.

**Comment by thuselem** [comment]
I like your interpretation more than mine.

**Comment by jviel** [comment]
Workin on this sucka

**Comment by thuselem** [comment]
An added note. The client says this is a paper form, and we don't need to implement any functionality for it.
