### ISSUE TITLE
Error when trying to update Provider that exists from within Operator Terminal

### ISSUE THREAD

**Issue by noah-mcaulay** [Gilmore-PDX-CS/Group9#79]
When trying to update a Provider from within the Operator Terminal it says that the Provider doesn't exists despite it existing. 

Current Output:

Provider ID : **100000017**
Name: This is broken
Address: fix me
City: now
State: TY
Zipcode: 12345
Enrollment Status: Active

@Operator Terminal 
For Patient:   (1) List All (2) Add  (3) Update  (4) Delete (5) Reinstate
For Provider:  (6) List All (7) Add  (8) Update  (9) Delete (10) Reinstate
Other:         (11) Exit Operator Terminal 
Enter option: 8
Please enter the ID of the patient to update: **100000017**
Provider **100000017** does not exist

**Comment by mbottini** [comment]
Pull request #84 submitted to fix this.

**Comment by jviel** [comment]
Tested and fixed
