### ISSUE TITLE
Update Service message confusing

### ISSUE THREAD

**Issue by thuselem** [Gilmore-PDX-CS/Group9#88]
Currently, when updating a service name the message is as follows:
```
Please add the new...
Please enter the service name: _
```
This is a bit confusing. Can we change the first line to something like:
```
Update Service name...
```

**Comment by andy-keene** [comment]
We cannot. I can change it to, "Enter the following information for the service to be updated" or 

"The following information will update service _x_.."

**Comment by thuselem** [comment]
Could we do, "Enter the following information for the service to be updated. The following information will update service x.. tobleronetobleronetoblerone"?

**Comment by andy-keene** [comment]
Probs tomorrow that should
Be fine

**Comment by andy-keene** [comment]
This good?
<img width="534" alt="screen shot 2016-11-25 at 1 19 32 pm" src="https://cloud.githubusercontent.com/assets/20017363/20635446/eb79413e-b311-11e6-8ecf-846bba2722c4.png">

**Comment by thuselem** [comment]
Yes, that looks great. Thanks.
