### ISSUE TITLE
Date input for Reports unclear

### ISSUE THREAD

**Issue by thuselem** [Gilmore-PDX-CS/Group9#90]
Currently, EFT, Summary and Provider ask for a date. Patient does not.

The message says:
```
Please enter a date:
```
Is the report for that dates activity? Reports should print one-weeks worth of reports. Use a message like:
``` 
Please enter starting date:
```

**Comment by andy-keene** [comment]
It's for testing. It prints the weeks reports prior to that date. There
wasn't enough test cases to confirm, so I added that prompt - it's not a
user requirement and should be removed.

When your done testing let me know and I'll take it out. It's set up to
pull the report for the week prior to the request

**Comment by thuselem** [comment]
You can take it out now. We only want to test user functionality at this point.
