### ISSUE TITLE
Block consultation for patients who have not been checked in

### ISSUE THREAD

**Issue by thuselem** [Gilmore-PDX-CS/Group9#91]
Currently, a provider can start a consultation for a patient who has not been checked in. Since patients are checked in to validate their financial standing, this should not be possible. We don't want to offer services to patients who haven't paid their dues.

**Comment by thuselem** [comment]
On re-reading the spec, I realized these are not necessarily sequential. I am downgrading this to low-priority and discussion.

**Comment by andy-keene** [comment]
Yeah, from what I recall it's the providers responsibility to use the terminal to "verify" a patient when they come in? 

There's no checking in, so to speak. And we verify their status, per requirements, as specified in the documentation.

**Comment by thuselem** [comment]
Yup. This is also a non-issue because a consultation cannot be started for a patient who is not validated.
